Ajout d'utilisateurs dans le script de creation de la db
OrifInformatique/gestion_questionnaires pull request #271
Opened 2020-08-17 07:28 UTC by jubnl

Ajout de 3 utilisateurs : 
- admin
- member
- manager
tous avec le mdp habituel de la section

2020-08-19 06:24 UTC, DidierViret commented
Le pull request doit être fait vers la branche Release 1.5, pas vers la branche master.

2020-08-19 06:35 UTC, jubnl commented
Je me suis trompé, je m'en occupe

Le mer. 19 août 2020 à 08:24, Didier Viret <notifications@github.com> a
écrit :

> Le pull request doit être fait vers la branche Release 1.5, pas vers la
> branche master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OrifInformatique/gestion_questionnaires/pull/271#issuecomment-675877750>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP5NBHE3R32WFDEQLMVRQKTSBNVZBANCNFSM4QBK6Y3A>
> .
>

2020-08-19 07:03 UTC, DidierViret requested changes

2020-08-19 07:03 UTC, DidierViret commented on application/controllers/Question.php
> +		 	switch($_GET['nb_questions']){
Il faut mettre juste des chiffres dans la liste déroulante à la place d'une chaîne de texte. ça qui évite d'utiliser un switch, on peut simplement écrire
```
if ($_GET['nb_questions'] == $this->lang->line('all_questions') {
    $items_per_page = count($output['questions']);
}  else {
    $items_per_page = $_GET['nb_questions'];
}
```
On y gagne beaucoup de souplesse si on veut plus tard ajouter d'autres valeurs que 25 - 50 -100.

2020-08-19 07:03 UTC, DidierViret commented on application/language/french/MY_application_lang.php
> +$lang['all_questions']                  = 'Tout';
Garder uniquement "all_questions" dans le fichier lang, les autres chaines ne contiennent que des chiffres et n'ont donc pas besoin d'être traduites, elles peuvent être dans le code, par exemple dans un tableau fourni par le fichier config ou dans une constante.
(voir autre commentaire dans le contrôleur Question)

2020-08-19 07:03 UTC, DidierViret commented on application/views/questions/index.php
> +                    $questions_all = $this->lang->line('all_questions');
Ces valeurs doivent être fournies par le contrôleur au moment de l'appel de la vue. Ce n'est pas à la vue d'aller les récupérer.

2020-08-19 07:09 UTC, jubnl commented on application/controllers/Question.php
> +		 	switch($_GET['nb_questions']){
Il faut ajouter un cas par défaut, c'est pour ça que j'avais pensé au switch au 1er abord. Lorsqu'on charge la page "gestion_questionnaires/question" $items_per_page n'est pas défini et donc ne charge pas d'items dans la vue

2020-08-28 12:12 UTC, DidierViret commented
J'ai testé la pagination mais elle ne fonctionne pas. A vérifier.

2020-08-28 12:36 UTC, jubnl commented
100% fonctionnel chez moi, le dernier commit concerne un petit bug qui réinitialisait la pagination lorsque le filtre "module" était changé.

2020-09-02 07:31 UTC, DidierViret approved these changes

2020-09-02 07:32 UTC, closed without merging